[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_BUN = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
